// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class elys : Exchange
{
    public elys (object args = null): base(args) {}

    public async Task<object> publicGetV1Currencies (object parameters = null)
    {
        return await this.callAsync ("publicGetV1Currencies",parameters);
    }

    public async Task<object> publicGetV1Markets (object parameters = null)
    {
        return await this.callAsync ("publicGetV1Markets",parameters);
    }

    public async Task<object> publicGetV1Tickers (object parameters = null)
    {
        return await this.callAsync ("publicGetV1Tickers",parameters);
    }

    public async Task<object> publicGetV1FundingRates (object parameters = null)
    {
        return await this.callAsync ("publicGetV1FundingRates",parameters);
    }

    public async Task<object> publicGetV1OrdersOpen (object parameters = null)
    {
        return await this.callAsync ("publicGetV1OrdersOpen",parameters);
    }

    public async Task<object> publicGetV1Orders (object parameters = null)
    {
        return await this.callAsync ("publicGetV1Orders",parameters);
    }

    public async Task<object> publicGetV1Order (object parameters = null)
    {
        return await this.callAsync ("publicGetV1Order",parameters);
    }

    public async Task<object> publicGetV1OpenInterest (object parameters = null)
    {
        return await this.callAsync ("publicGetV1OpenInterest",parameters);
    }

    public async Task<object> publicGetTradesAddressSymbolSizeFrom (object parameters = null)
    {
        return await this.callAsync ("publicGetTradesAddressSymbolSizeFrom",parameters);
    }

}