# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.elys import ImplicitAPI
import math
from ccxt.base.types import Any, Balances, Currencies, Int, Market, Strings, Ticker, Tickers, Trade
from typing import List
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.decimal_to_precision import TICK_SIZE


class elys(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(elys, self).describe(), {
            'id': 'elys',
            'name': 'Elys Network',
            'countries': ['US'],  # United States
            'version': 'v1',
            'rateLimit': 100,  # 10 requests per second
            'certified': False,
            'pro': False,
            'dex': True,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': True,
                'future': True,
                'option': False,
                'addMargin': False,
                'borrowCrossMargin': False,
                'borrowIsolatedMargin': False,
                'cancelAllOrders': False,
                'cancelAllOrdersAfter': False,
                'cancelOrder': False,
                'cancelOrders': False,
                'cancelOrdersForSymbols': False,
                'closeAllPositions': False,
                'closePosition': False,
                'createMarketBuyOrderWithCost': False,
                'createMarketOrderWithCost': False,
                'createMarketSellOrderWithCost': False,
                'createOrder': False,
                'createOrders': False,
                'createOrderWithTakeProfitAndStopLoss': False,
                'createReduceOnlyOrder': False,
                'createStopOrder': False,
                'createTriggerOrder': False,
                'editOrder': False,
                'editOrders': False,
                'fetchAccounts': False,
                'fetchBalance': True,
                'fetchBorrowInterest': False,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchCanceledAndClosedOrders': False,
                'fetchCanceledOrders': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': True,
                'fetchDepositAddress': False,
                'fetchDepositAddresses': False,
                'fetchDeposits': False,
                'fetchDepositWithdrawFee': False,
                'fetchDepositWithdrawFees': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchLedger': False,
                'fetchLeverage': False,
                'fetchLeverageTiers': False,
                'fetchLiquidations': False,
                'fetchMarginMode': None,
                'fetchMarketLeverageTiers': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyLiquidations': False,
                'fetchMyTrades': True,
                'fetchOHLCV': True,
                'fetchOpenInterest': False,
                'fetchOpenInterestHistory': False,
                'fetchOpenInterests': False,
                'fetchOpenOrders': False,
                'fetchOrder': False,
                'fetchOrderBook': False,
                'fetchOrders': False,
                'fetchOrderTrades': False,
                'fetchPosition': False,
                'fetchPositionMode': False,
                'fetchPositions': False,
                'fetchPositionsRisk': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': 'emulated',
                'fetchTickers': True,
                'fetchTime': False,
                'fetchTrades': False,
                'fetchTradingFee': False,
                'fetchTradingFees': False,
                'fetchTransfer': False,
                'fetchTransfers': False,
                'fetchWithdrawals': False,
                'repayCrossMargin': False,
                'repayIsolatedMargin': False,
                'setLeverage': False,
                'setMarginMode': False,
                'setPositionMode': False,
                'signIn': False,
                'transfer': False,
                'withdraw': False,
            },
            'timeframes': {
                '1m': '1',
                '1h': '60',
                '1d': '1D',
            },
            'urls': {
                'logo': 'https://elys.network/logo.png',
                'api': {
                    'public': 'https://testnet-elys-ccxt-service-j5trp.ondigitalocean.app',
                    'private': 'https://testnet-elys-ccxt-service-j5trp.ondigitalocean.app',
                },
                'test': {
                    'public': 'https://testnet-elys-ccxt-service-j5trp.ondigitalocean.app',
                    'private': 'https://testnet-elys-ccxt-service-j5trp.ondigitalocean.app',
                },
                'www': 'https://elys.network',
                'doc': [
                    'https://docs.elys.network',
                ],
                'fees': [
                    'https://docs.elys.network/developers/fees',
                ],
            },
            'api': {
                'public': {
                    'get': {
                        'v1/currencies': 1,
                        'v1/markets': 1,
                        'v1/tickers': 1,
                    },
                },
            },
            'fees': {
                'trading': {
                    'feeSide': 'get',
                    'tierBased': False,
                    'percentage': True,
                    'taker': self.parse_number('0.001'),  # 0.1%
                    'maker': self.parse_number('0.001'),  # 0.1%
                },
            },
            'precisionMode': TICK_SIZE,
            'exceptions': {
                'exact': {},
                'broad': {},
            },
            'options': {
                'sandboxMode': False,
                'defaultType': 'swap',  # 'spot', 'swap'
                'defaultSubType': 'linear',  # 'linear', 'inverse'
            },
            'commonCurrencies': {},
        })

    def set_sandbox_mode(self, enabled):
        super(elys, self).set_sandbox_mode(enabled)
        self.options['sandboxMode'] = enabled

    async def fetch_currencies(self, params={}) -> Currencies:
        """
        fetches all available currencies on an exchange
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: an associative dictionary of currencies
        """
        url = self.urls['api']['public'] + '/v1/currencies'
        response = await self.fetch(url, 'GET', None, None)
        #
        # [
        #     {
        #         "decimals": 6,
        #         "denom": "USDC"
        #     },
        #     {
        #         "decimals": 8,
        #         "denom": "WBTC"
        #     }
        # ]
        #
        result: dict = {}
        for i in range(0, len(response)):
            currency = response[i]
            id = self.safe_string(currency, 'denom')
            code = self.safe_currency_code(id)
            decimals = self.safe_integer(currency, 'decimals')
            result[code] = self.safe_currency_structure({
                'id': id,
                'name': id,
                'code': code,
                'precision': decimals,
                'info': currency,
                'active': True,
                'deposit': None,
                'withdraw': None,
                'networks': None,
                'fee': None,
                'type': 'crypto',
                'limits': {
                    'amount': {
                        'min': None,
                        'max': None,
                    },
                    'withdraw': {
                        'min': None,
                        'max': None,
                    },
                },
            })
        return result

    async def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for elys
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: an array of objects representing market data
        """
        url = self.urls['api']['public'] + '/v1/markets'
        response = await self.fetch(url, 'GET', None, None)
        #
        # {
        #     "amm_pools": [
        #         {
        #             "pool_assets": [
        #                 {
        #                     "token": {
        #                         "amount": "1000000",
        #                         "denom": "WBTC"
        #                     },
        #                     "weight": "50"
        #                 },
        #                 {
        #                     "token": {
        #                         "amount": "50000000000",
        #                         "denom": "USDC"
        #                     },
        #                     "weight": "50"
        #                 }
        #             ],
        #             "pool_id": 1,
        #             "pool_params": {
        #                 "fee_denom": "USDC",
        #                 "swap_fee": "0.003"
        #             }
        #         }
        #     ]
        # }
        #
        result = []
        ammPools = self.safe_list(response, 'amm_pools', [])
        for i in range(0, len(ammPools)):
            pool = ammPools[i]
            poolAssets = self.safe_list(pool, 'pool_assets', [])
            if len(poolAssets) >= 2:
                baseAsset = poolAssets[0]
                quoteAsset = poolAssets[1]
                baseToken = self.safe_dict(baseAsset, 'token', {})
                quoteToken = self.safe_dict(quoteAsset, 'token', {})
                baseId = self.safe_string(baseToken, 'denom')
                quoteId = self.safe_string(quoteToken, 'denom')
                base = self.safe_currency_code(baseId)
                quote = self.safe_currency_code(quoteId)
                poolId = self.safe_string(pool, 'pool_id')
                symbol = base + '/' + quote
                poolParams = self.safe_dict(pool, 'pool_params', {})
                swapFee = self.safe_string(poolParams, 'swap_fee')
                result.append(self.safe_market_structure({
                    'id': poolId,
                    'symbol': symbol,
                    'base': base,
                    'quote': quote,
                    'settle': None,
                    'baseId': baseId,
                    'quoteId': quoteId,
                    'settleId': None,
                    'type': 'swap',
                    'spot': False,
                    'margin': False,
                    'swap': True,
                    'future': False,
                    'option': False,
                    'active': True,
                    'contract': True,
                    'linear': True,
                    'inverse': False,
                    'taker': self.parse_number(swapFee),
                    'maker': self.parse_number(swapFee),
                    'contractSize': None,
                    'expiry': None,
                    'expiryDatetime': None,
                    'strike': None,
                    'optionType': None,
                    'precision': {
                        'amount': None,
                        'price': None,
                    },
                    'limits': {
                        'leverage': {
                            'min': None,
                            'max': None,
                        },
                        'amount': {
                            'min': None,
                            'max': None,
                        },
                        'price': {
                            'min': None,
                            'max': None,
                        },
                        'cost': {
                            'min': None,
                            'max': None,
                        },
                    },
                    'created': None,
                    'info': pool,
                }))
        return result

    async def fetch_tickers(self, symbols: Strings = None, params={}) -> Tickers:
        """
        fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
        :param str[]|None symbols: unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a dictionary of ticker structures
        """
        await self.load_markets()
        request: dict = {}
        if symbols is not None:
            marketIds = []
            for i in range(0, len(symbols)):
                symbol = symbols[i]
                market = self.market(symbol)
                marketIds.append(market['base'] + '-' + market['quote'])
            request['symbols'] = marketIds
        url = self.urls['api']['public'] + '/v1/tickers'
        response = await self.fetch(url, 'GET', None, None)
        #
        # [
        #     {
        #         "instrument": "WBTC-USDC",
        #         "period24h": {
        #             "change": 1250.5,
        #             "changePercentage": 2.5,
        #             "high": 52000.0,
        #             "low": 49500.0,
        #             "open": 50000.0,
        #             "volume": 1500000.0
        #         },
        #         "price": 51250.5,
        #         "priceUsd": "51250.5",
        #         "timestamp": 1640995200000
        #     }
        # ]
        #
        result: dict = {}
        for i in range(0, len(response)):
            ticker = self.parse_ticker(response[i])
            symbol = ticker['symbol']
            result[symbol] = ticker
        return self.filter_by_array_tickers(result, 'symbol', symbols)

    def parse_ticker(self, ticker, market: Market = None) -> Ticker:
        #
        # {
        #     "instrument": "WBTC-USDC",
        #     "period24h": {
        #         "change": 1250.5,
        #         "changePercentage": 2.5,
        #         "high": 52000.0,
        #         "low": 49500.0,
        #         "open": 50000.0,
        #         "volume": 1500000.0
        #     },
        #     "price": 51250.5,
        #     "priceUsd": "51250.5",
        #     "timestamp": 1640995200000
        # }
        #
        marketId = self.safe_string(ticker, 'instrument')
        symbol = self.safe_symbol(marketId, market, '-')
        timestamp = self.safe_integer(ticker, 'timestamp')
        period24h = self.safe_dict(ticker, 'period24h', {})
        last = self.safe_string(ticker, 'price')
        open = self.safe_string(period24h, 'open')
        high = self.safe_string(period24h, 'high')
        low = self.safe_string(period24h, 'low')
        change = self.safe_string(period24h, 'change')
        percentage = self.safe_string(period24h, 'changePercentage')
        baseVolume = self.safe_string(period24h, 'volume')
        return self.safe_ticker({
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': high,
            'low': low,
            'bid': None,
            'bidVolume': None,
            'ask': None,
            'askVolume': None,
            'vwap': None,
            'open': open,
            'close': last,
            'last': last,
            'previousClose': None,
            'change': change,
            'percentage': percentage,
            'average': None,
            'baseVolume': baseVolume,
            'quoteVolume': None,
            'info': ticker,
        }, market)

    async def fetch_ohlcv(self, symbol: str, timeframe='1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        """
        fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
        :param str symbol: unified symbol of the market to fetch OHLCV data for
        :param str timeframe: the length of time each candle represents, support '1m', '1h', '1d'
        :param int [since]: timestamp in ms of the earliest candle to fetch
        :param int [limit]: the maximum amount of candles to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param int [params.until]: timestamp in ms of the latest candle to fetch
        :returns int[][]: A list of candles ordered, open, high, low, close, volume
        """
        await self.load_markets()
        market = self.market(symbol)
        until = self.safe_integer(params, 'until', self.milliseconds())
        fromTime = since
        if fromTime is None:
            if limit is not None:
                timeframeInMilliseconds = self.parse_timeframe(timeframe) * 1000
                fromTime = self.sum(until, timeframeInMilliseconds * limit * -1)
            else:
                fromTime = 0
        fromTime = int(math.floor(fromTime / 1000))  # convert to seconds
        toTime = int(math.floor(until / 1000))  # convert to seconds
        params = self.omit(params, ['until'])
        path = 'ohlcv/' + market['baseId'] + '/' + str(fromTime) + '/' + str(toTime) + '/' + self.safe_string(self.timeframes, timeframe, timeframe)
        url = self.urls['api']['public'] + '/' + path
        response = await self.fetch(url, 'GET', None, None)
        #
        # [
        #     {
        #         "close": 51000.0,
        #         "high": 51500.0,
        #         "low": 50500.0,
        #         "open": 50800.0,
        #         "timestamp": 1640995200
        #     }
        # ]
        #
        return self.parse_ohlcvs(response, market, timeframe, since, limit)

    def parse_ohlcv(self, ohlcv, market: Market = None) -> list:
        #
        # {
        #     "close": 51000.0,
        #     "high": 51500.0,
        #     "low": 50500.0,
        #     "open": 50800.0,
        #     "timestamp": 1640995200
        # }
        #
        return [
            self.safe_timestamp(ohlcv, 'timestamp'),
            self.safe_number(ohlcv, 'open'),
            self.safe_number(ohlcv, 'high'),
            self.safe_number(ohlcv, 'low'),
            self.safe_number(ohlcv, 'close'),
            None,  # volume not provided in response
        ]

    async def fetch_balance(self, params={}) -> Balances:
        """
        query for balance and get the amount of funds available for trading or funds locked in orders
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str params['address']: the wallet address to fetch balance for
        :returns dict: a balance structure
        """
        address = self.safe_string(params, 'address')
        if address is None:
            raise ArgumentsRequired(self.id + ' fetchBalance() requires an address parameter')
        params = self.omit(params, ['address'])
        path = 'v1/balance/' + address
        url = self.urls['api']['public'] + '/' + path
        response = await self.fetch(url, 'GET', None, None)
        #
        # {
        #     "leverage_lp_positions": [...],
        #     "liquid_assets": [
        #         {
        #             "amount": "1000000000",
        #             "denom": "USDC"
        #         },
        #         {
        #             "amount": "50000000",
        #             "denom": "WBTC"
        #         }
        #     ],
        #     "liquidity_positions": [...],
        #     "perpetual_positions": [...]
        # }
        #
        result: dict = {
            'info': response,
            'timestamp': None,
            'datetime': None,
        }
        liquidAssets = self.safe_list(response, 'liquid_assets', [])
        for i in range(0, len(liquidAssets)):
            balance = liquidAssets[i]
            currencyId = self.safe_string(balance, 'denom')
            code = self.safe_currency_code(currencyId)
            amount = self.safe_string(balance, 'amount')
            account = self.account()
            account['free'] = amount
            account['total'] = amount
            result[code] = account
        return self.safe_balance(result)

    async def fetch_my_trades(self, symbol: str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        fetch all trades made by the user
        :param str symbol: unified market symbol
        :param int [since]: the earliest time in ms to fetch trades for
        :param int [limit]: the maximum number of trades structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str params['address']: the wallet address to fetch trades for
        :param int [params.from]: pagination offset, defaults to 0
        :returns Trade[]: a list of trade structures
        """
        if symbol is None:
            raise ArgumentsRequired(self.id + ' fetchMyTrades() requires a symbol parameter')
        await self.load_markets()
        market = self.market(symbol)
        address = self.safe_string(params, 'address')
        if address is None:
            raise ArgumentsRequired(self.id + ' fetchMyTrades() requires an address parameter')
        fromParam = self.safe_string(params, 'from', '0')
        size = self.safe_string(params, 'size', str(limit) if limit else '100')
        params = self.omit(params, ['address', 'from', 'size'])
        # Convert symbol to API format(base-quote)
        symbolId = market['base'] + '-' + market['quote']
        path = 'trades/' + address + '/' + symbolId + '/' + size + '/' + fromParam
        url = self.urls['api']['public'] + '/' + path
        response = await self.fetch(url, 'GET', None, None)
        #
        # {
        #     "perpetual_position": [
        #         {
        #             "all_interests_paid": "string",
        #             "amm_pool_id": "string",
        #             "borrow_interest_paid_custody": "string",
        #             "closing_amount": "string",
        #             "closing_price": "string",
        #             "closing_ratio": "string",
        #             "collateral": "string",
        #             "collateral_amount": "string",
        #             "collateral_asset": "string",
        #             "created_at": "2019-08-24T14:15:22Z",
        #             "custody": "string",
        #             "custody_asset": "string",
        #             # ... more fields
        #             "txhash": "string",
        #             "type": "string"
        #         }
        #     ],
        #     "spot_orders": [
        #         {
        #             "amount": {
        #                 "amount": "string",
        #                 "denom": "string"
        #             },
        #             "created_at": "2019-08-24T14:15:22Z",
        #             "order_amount": {
        #                 "amount": "string",
        #                 "denom": "string"
        #             },
        #             "order_id": "string",
        #             "order_price": "string",
        #             "order_type": "string",
        #             "owner_address": "string",
        #             "spot_price": "string",
        #             "txhash": "string",
        #             "type": "string"
        #         }
        #     ]
        # }
        #
        result = []
        # Process perpetual position trades
        perpetualPositions = self.safe_list(response, 'perpetual_position', [])
        for i in range(0, len(perpetualPositions)):
            trade = self.parse_my_trade(perpetualPositions[i], market)
            result.append(trade)
        # Process spot order trades
        spotOrders = self.safe_list(response, 'spot_orders', [])
        for i in range(0, len(spotOrders)):
            trade = self.parse_my_trade(spotOrders[i], market)
            result.append(trade)
        return self.filter_by_since_limit(result, since, limit, 'timestamp')

    def parse_my_trade(self, trade, market: Market = None) -> Trade:
        #
        # Perpetual position trade:
        # {
        #     "all_interests_paid": "string",
        #     "amm_pool_id": "string",
        #     "closing_amount": "string",
        #     "closing_price": "string",
        #     "collateral_amount": "string",
        #     "created_at": "2019-08-24T14:15:22Z",
        #     "open_price": "string",
        #     "owner": "string",
        #     "position": "string",
        #     "txhash": "string",
        #     "type": "string"
        # }
        #
        # Spot order trade:
        # {
        #     "amount": {
        #         "amount": "string",
        #         "denom": "string"
        #     },
        #     "created_at": "2019-08-24T14:15:22Z",
        #     "order_amount": {
        #         "amount": "string",
        #         "denom": "string"
        #     },
        #     "order_id": "string",
        #     "order_price": "string",
        #     "order_type": "string",
        #     "owner_address": "string",
        #     "spot_price": "string",
        #     "txhash": "string",
        #     "type": "string"
        # }
        #
        id = self.safe_string_2(trade, 'txhash', 'order_id')
        timestamp = self.parse8601(self.safe_string(trade, 'created_at'))
        symbol = market['symbol'] if market else None
        # Determine if it's a perpetual or spot trade
        isPerpetual = ('amm_pool_id' in trade)
        amount: str
        price: str
        side: str
        type: str
        if isPerpetual:
            # Perpetual position trade(can be open or closed)
            amount = self.safe_string(trade, 'collateral')  # Use collateral position size
            price = self.safe_string(trade, 'open_price')  # Use open_price for perpetual positions
            side = self.safe_string(trade, 'position')  # 'long' or 'short'
            type = 'market'  # perpetual positions are typically market orders
        else:
            # Spot order trade
            orderAmount = self.safe_dict(trade, 'order_amount', {})
            amount = self.safe_string(orderAmount, 'amount')
            price = self.safe_string_2(trade, 'order_price', 'spot_price')
            orderType = self.safe_string(trade, 'order_type')
            side = 'buy' if (orderType == 'buy') else 'sell'
            type = 'market'  # assuming market orders for now
        cost = self.number_to_string(self.parse_number(amount) * self.parse_number(price)) if (amount and price) else None
        return self.safe_trade({
            'id': id,
            'order': self.safe_string(trade, 'order_id'),
            'info': trade,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'type': type,
            'side': side,
            'amount': amount,
            'price': price,
            'cost': cost,
            'fee': None,  # fee information not directly available
            'takerOrMaker': None,
        }, market)
