<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class elys extends \ccxt\Exchange {
    public function public_get_v1_currencies($params = array()) {
        return $this->request('v1/currencies', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_v1_markets($params = array()) {
        return $this->request('v1/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_v1_tickers($params = array()) {
        return $this->request('v1/tickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1Currencies($params = array()) {
        return $this->request('v1/currencies', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1Markets($params = array()) {
        return $this->request('v1/markets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetV1Tickers($params = array()) {
        return $this->request('v1/tickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
